#!/bin/bash

INP="$(zenity --entry --width=320 --text='Percents (to hexadecimal)' 2> /dev/null)"
[ "$INP" = "" ] && exit

RES="$(printf '%02x' $(( "$INP" * 255 / 100 )))"

echo -n "$RES" | xclip -selection c
zenity --info --width=400 --text="<span size='xx-large' face='monospace'>$RES</span>\n\n(copied to clipboard)" 2> /dev/null
